(() => {
  const regions = [
    {name:'Western Coast & Colombo', tag:'City • Coast • Food', desc:'A fast-moving gateway where modern Colombo meets beaches, lagoons, markets and everyday island life.', places:['Colombo','Negombo','Kalutara'], experiences:['City life & food','Coastal escapes','Markets & local life'], route:'Colombo → Negombo → Kalutara', days:'2–4 days', styles:['First trip','Food','City + coast']},
    {name:'South Coast', tag:'Beach • Heritage • Slow travel', desc:'Golden beaches, surf towns, whale-watching waters and the layered streets of Galle Fort.', places:['Galle','Unawatuna','Mirissa','Weligama','Tangalle'], experiences:['Galle Fort','Surf & beaches','Whale watching'], route:'Galle → Weligama → Mirissa → Tangalle', days:'4–7 days', styles:['Beach','Couples','Slow travel']},
    {name:'Hill Country', tag:'Tea • Mountains • Scenic', desc:'Cooler air, tea-covered slopes, misty viewpoints and some of the island’s most memorable rail and road journeys.', places:['Kandy','Nuwara Eliya','Ella'], experiences:['Tea country','Mountain walks','Scenic train journeys'], route:'Kandy → Nuwara Eliya → Ella', days:'3–6 days', styles:['Scenic','Nature','Slow travel']},
    {name:'Cultural Triangle', tag:'Heritage • Ancient cities • Sacred places', desc:'A concentrated journey through ancient kingdoms, monumental sites, cave temples and living spiritual traditions.', places:['Sigiriya','Dambulla','Anuradhapura','Polonnaruwa'], experiences:['Ancient cities','Sigiriya','Sacred heritage'], route:'Dambulla → Sigiriya → Polonnaruwa → Anuradhapura', days:'3–5 days', styles:['Culture','History','First trip']},
    {name:'East Coast', tag:'Sunrise • Surf • Quiet bays', desc:'Open horizons, warm seas, surf breaks, lagoons and a slower coastal rhythm during the island’s eastern season.', places:['Trincomalee','Nilaveli','Arugam Bay','Pasikuda'], experiences:['Surfing','Beach days','East-coast culture'], route:'Trincomalee → Nilaveli → Arugam Bay', days:'4–7 days', styles:['Beach','Surf','Adventure']},
    {name:'North', tag:'Culture • Islands • Local character', desc:'A distinctive side of Sri Lanka shaped by Tamil culture, islands, historic sites, food and wide northern landscapes.', places:['Jaffna','Delft Island','Mannar'], experiences:['Northern food','Jaffna culture','Island journeys'], route:'Jaffna → Delft → Mannar', days:'3–5 days', styles:['Culture','Offbeat','Local life']},
    {name:'North Central', tag:'Wildlife • Lakes • Ancient landscapes', desc:'A quieter landscape of reservoirs, forests, wildlife and archaeological places beyond the classic triangle route.', places:['Minneriya','Habarana','Wasgamuwa'], experiences:['Wildlife','Village life','Ancient landscapes'], route:'Habarana → Minneriya → Wasgamuwa', days:'2–4 days', styles:['Wildlife','Nature','Family']},
    {name:'Uva & Sabaragamuwa', tag:'Waterfalls • Forests • Adventure', desc:'A greener, less hurried side of the island with forests, waterfalls, mountain trails and routes made for discovery.', places:['Ratnapura','Kitulgala','Badulla','Haputale'], experiences:['Waterfalls','Hiking','Rainforest & adventure'], route:'Kitulgala → Ratnapura → Haputale → Badulla', days:'3–6 days', styles:['Adventure','Nature','Offbeat']}
  ];
  const grid=document.getElementById('v28-region-grid'); const panel=document.getElementById('v28-region-panel'); if(!grid||!panel)return;
  grid.innerHTML=regions.map((r,i)=>`<article class="v28-card" data-region="${i}"><span class="v28-num">0${i+1}</span><div><span class="v28-tag">${r.tag}</span><h3>${r.name}</h3><p>${r.desc}</p></div><button type="button" class="v28-open">Explore region <span>→</span></button></article>`).join('');
  function open(i){const r=regions[i]; panel.hidden=false; panel.innerHTML=`<div class="v28-panel-inner"><button class="v28-close" type="button">Close ×</button><div class="v28-panel-copy"><span class="v28-tag">${r.tag}</span><h3>${r.name}</h3><p>${r.desc}</p><div class="v28-facts"><div><small>PLACES</small><strong>${r.places.join(' · ')}</strong></div><div><small>SIGNATURE EXPERIENCES</small><strong>${r.experiences.join(' · ')}</strong></div><div><small>GOOD FOR</small><strong>${r.styles.join(' · ')}</strong></div><div><small>IDEAL TIME</small><strong>${r.days}</strong></div></div><div class="v28-route"><small>SCENIC FLOW</small><strong>${r.route}</strong></div><div class="v28-panel-actions"><button type="button" class="v28-journey" data-region-name="${r.name}">Add region to My Journey →</button><a href="#journey-workspace">Open Journey Workspace</a></div></div></div>`; panel.scrollIntoView({behavior:'smooth',block:'start'}); panel.querySelector('.v28-close').onclick=()=>{panel.hidden=true}; panel.querySelector('.v28-journey').onclick=()=>{try{localStorage.setItem('lankaoraRegionIntent',r.name)}catch(e){}; panel.querySelector('.v28-journey').textContent='Region saved to your journey ✓';};}
  grid.addEventListener('click',e=>{const c=e.target.closest('.v28-card');if(c)open(Number(c.dataset.region));});
})();
